server:
  port: 10001

spring:
  cloud:
    gateway:
      routes:
        - id: api-service
          uri: lb://aba-api-service
          predicates:
            - Path=/api/**
  redis:
    host: 117.72.40.28
    port: 6379
    password: dIk&954.#326

dubbo:
  application:
    name: dubbo-aba-api-service
  protocol:
    name: dubbo
    port: -1
  registry:
#    address: nacos://117.72.40.28:8848
    address: nacos://localhost:8848
    parameters:
      namespace: 4ae9a459-9e4a-4371-bd04-60c8fc08aeb1
      group: aba-api
      register-consumer-url: true
