server:
  port: 10002

spring:
  redis:
    host: 192.168.10.11
    port: 6379
    password: root
  cloud:
    gateway:
      routes:
        - id: forward
          uri: no://op
          predicates:
            - Header=dataId, ^.{32}$

dubbo:
  application:
    name: dubbo-aba-api-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.10.11:8848
    parameters:
      namespace: 4ae9a459-9e4a-4371-bd04-60c8fc08aeb1
      group: aba-api
      register-consumer-url: true
