server:
  port: 10010

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.11:3306/aba_api?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: 192.168.10.11
    port: 6379
    password: root

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cloud.zfwproject.abaapi.service.model.po

