server:
  port: 10010
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.40.28:3306/aba_api?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: dIk&954.#326
  redis:
    host: 117.72.40.28
    port: 6379
    password: dIk&954.#326
  kafka:
    bootstrap-servers: 117.72.40.28:9092
    consumer:
      group-id: interface-audit-group

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cloud.zfwproject.abaapi.service.model.po

dubbo:
  application:
    name: dubbo-aba-api-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
#    address: nacos://117.72.40.28:8848
    parameters:
      namespace: 4ae9a459-9e4a-4371-bd04-60c8fc08aeb1
      group: aba-api
